version: "3.7"

services:
  app1:
    image: httpd:latest
    container_name: app1
    ports:
      - 8080:80
    networks:
      - app1_net

#cria uma network via docker compose
networks:
  app1_net: